"use strict";
(function (KEY_CODE) {
    KEY_CODE[KEY_CODE["RIGHT_ARROW"] = 39] = "RIGHT_ARROW";
    KEY_CODE[KEY_CODE["LEFT_ARROW"] = 37] = "LEFT_ARROW";
    KEY_CODE[KEY_CODE["UP_ARROW"] = 38] = "UP_ARROW";
    KEY_CODE[KEY_CODE["DOWN_ARROW"] = 40] = "DOWN_ARROW";
    KEY_CODE[KEY_CODE["ENTER_KEY"] = 13] = "ENTER_KEY";
    KEY_CODE[KEY_CODE["SPACE_BAR"] = 32] = "SPACE_BAR";
    KEY_CODE[KEY_CODE["LEFT_BRACKET"] = 219] = "LEFT_BRACKET";
    KEY_CODE[KEY_CODE["RIGHT_BRACKET"] = 221] = "RIGHT_BRACKET";
    KEY_CODE[KEY_CODE["LESS_THAN"] = 188] = "LESS_THAN";
    KEY_CODE[KEY_CODE["GREATER_THAN"] = 190] = "GREATER_THAN";
})(exports.KEY_CODE || (exports.KEY_CODE = {}));
var KEY_CODE = exports.KEY_CODE;
